name: Release cv pdf

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "en/**"
      - "ru/**"
      - ".github/workflows/build_cv.yaml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build CV's from latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            en/Dmitry_Moskalenko_CV.tex
            ru/Dmitry_Moskalenko_CV.tex

      - name: Add cv to git
        run: git add --all

      - name: Update files on GitHub
        uses: test-room-7/action-update-file@v1.8.0
        with:
          file-path: |
            en/Dmitry_Moskalenko_CV.pdf
            ru/Dmitry_Moskalenko_CV.pdf
          commit-msg: "chore: update cv files [skip ci]"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-removing: true

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: |
            en/Dmitry_Moskalenko_CV.pdf
            ru/Dmitry_Moskalenko_CV.pdf

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: cv

      - name: Rename cv files
        run: |
          mv en/Dmitry_Moskalenko_CV.pdf en/Dmitry_Moskalenko_CV_EN.pdf
          mv ru/Dmitry_Moskalenko_CV.pdf ru/Dmitry_Moskalenko_CV_RU.pdf

      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          tag_template: "yyyy.mm.dd.i"

      - name: Upload cv to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            en/Dmitry_Moskalenko_CV_EN.pdf
            ru/Dmitry_Moskalenko_CV_RU.pdf
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: CV ${{ steps.generate_release_tag.outputs.next_release_tag }}
