name: Build RU cv

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "ru/**"

jobs:
  build-latex:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile CV from latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ru/Dmitry_Moskalenko_CV.tex

      - name: Upload cv to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ru/Dmitry_Moskalenko_CV.tex
