name: Build RU cv

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "ru/**"

jobs:
  build-latex:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ru/Dmitry_Moskalenko_CV.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Dmitry_Moskalenko_CV_${{ github.sha }}
          path: ./ru/Dmitry_Moskalenko_CV.pdf
