name: Build LaTeX document

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "en/**"

jobs:
  build-latex:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: en/Dmitry_Moskalenko_CV.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Dmitry_Moskalenko_CV_${{ github.sha }}
          path: ./en/Dmitry_Moskalenko_CV.pdf

      - name: Add PDF file to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: build pdf from tex [skip ci]"
          repository: ./en
